// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ClassDemoDBEntityFRamework.model
{
    [Table("Pizza")]
    public partial class Pizza
    {
        [Key]
        public int Nr { get; set; }
        [Required]
        [StringLength(70)]
        public string Description { get; set; }
        public bool FamilyPizza { get; set; }
        public int Price { get; set; }
    }
}